### ISSUE TITLE
Input data structure for beeswarm plots

### ISSUE THREAD

**Issue by xsvato01** [MultiQC/MultiQC#1767]
Hi, I am unable to produce any custom beeswarm plots. I tried to plot one of your test data files located at [`/with_config/table_headerconfig`](https://github.com/ewels/MultiQC_TestData/tree/master/data/custom_content/with_config/table_headerconfig). From what I read on https://multiqc.info/docs/#beeswarm-plots-dot-plots I supposed the input data structure should be the same as for tables. Yet, when I edit the `multiqc_config.yaml ´to "beeswarm" I am getting the following:
```
custom_content | Not able to parse custom data in sequencing_stats.txt
```

REGEX:
`multiqc_config.yaml`
```yaml
custom_data:
    sequencing_stats:
        plot_type: 'beeswarm'
sp:
    sequencing_stats:
        fn: 'sequencing_stats.txt'
```
`sequencing_stats.txt`
```
Sample Name	Total reads	MBp	%Q30
samp_1	10293	3238472	87
samp_2	18892	3218892	74
samp_3	16384	2982834	88
```

Any ideas would me much appreciated!

**Comment by a-frantz** [comment]
@ewels Hi Phil. I'm also having trouble with custom content beeswarms. My data is correctly parsed and presented as a table, but it would be much easier to view the data as a beeswarm. According to the docs I've found, I shouldn't need to do anything different to get my table switched to a beeswarm. 

Here's the relevant snippets from the config I have:
```
custom_data:
  global_PHRED_scores:
    file_format: "tsv"
    section_name: "Global PHRED scores"
    plot_type: "beeswarm"
sp:
  global_PHRED_scores:
    fn: "*.global_PHRED_scores.tsv"
```
An example file: 
[SJBT033400_D1.RNA-Seq.global_PHRED_scores.tsv.txt](https://github.com/MultiQC/MultiQC/files/14057502/SJBT033400_D1.RNA-Seq.global_PHRED_scores.tsv.txt)
(note I had to add a `.txt` extension for some reason to upload this. Strange behavior from GH if you ask me)

And the resulting error message:
```
[2024-01-25 12:40:05,657] multiqc.modules.custom_content.custom_content      [DEBUG  ]  Not able to figure out a plot type for 'SJLGG034380_D1.RNA-Seq.global_PHRED_scores.tsv' plot type = beeswarm, all numeric = True, first row str = 28
[2024-01-25 12:40:05,657] multiqc.modules.custom_content.custom_content      [WARNING]  Not able to parse custom data in SJLGG034380_D1.RNA-Seq.global_PHRED_scores.tsv
```
