### ISSUE TITLE
Per-table sample name cleaning

### ISSUE THREAD

**Issue by ewels** [MultiQC/MultiQC#2097]
### Description of feature

Related to https://github.com/ewels/MultiQC/issues/542 but a simpler concept, to get us started.

New config option + back end code to allow sample name cleaning that is scoped to a specific table ID.

This allows us to collapse non-overlapping table rows for a specific table (eg. General Stats) without collapsing samples in other sections of the report.

Suggested config could look like:

```yml
table_specific_fn_clean_exts:
    general_stats_table:
        - _R1
        - _R2
```

As with current sample name cleaning, if duplicates are encountered, they are overwritten. (Better handling will be tackled in #542).
