### ISSUE TITLE
bclconvert module not incorporating log files into source list

### ISSUE THREAD

**Issue by KyleStiers** [MultiQC/MultiQC#2448]
### Description of bug

The BCL Convert docs say these are the matching patterns:

```yaml
bclconvert/runinfo:
  fn: RunInfo.xml
bclconvert/demux:
  fn: Demultiplex_Stats.csv
bclconvert/quality_metrics:
  fn: Quality_Metrics.csv
bclconvert/adaptermetrics:
  fn: Adapter_Metrics.csv
bclconvert/unknown_barcodes:
  fn: Top_Unknown_Barcodes.csv
````

however, in multiple versions tested (1.21, 1.19, 1.18, 1.15) only the Demultiplex_Stats.csv file gets listed as a source - as evidenced by the `multiqc_sources.txt` and the `multiqc_data.json` files. I briefly looked through the module's code and it does appear to bring in and parse the other files (for example `Quality_Metrics.csv`) and I see historical issues mentioning this file, but I don't see it incorporated into the list of sources and I don't see the specific tabular data being incorporated.

It seems like the module actually is pulling the data in, for example the Mean Quality Score column might be coming correctly from Quality_Metrics.csv, but the `--verbose` logs nor any of the "source" outputs by MultiQC confirm this. Can someone confirm that it is in fact pulling in that data and what the rationale was for not storing it in blocks specific to which log file it came from in the json or at least mentioning it was used in the sources? I don't mean to split hairs, but it is somewhat misleading.

I also tested this on the provided test-data (which only goes up to 3.9.3) and got the same result with only the singular Demultiplex_Stats.csv being listed under `report_data_sources` in by `..bysample` block.

### File that triggers the error

[Link to MQC's own test data that can replicate the issue](https://github.com/MultiQC/test-data/tree/main/data/modules/bclconvert/3.9.3)

### MultiQC Error log

```console
No error as it completes successfully.
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.
