### ISSUE TITLE
Config file seemingly not being respected

### ISSUE THREAD

**Issue by stkgo** [MultiQC/MultiQC#2795]
### Description of bug

I have the following config file 

```
max_table_rows: 100000

table_columns_placement:
  general_stats_table:
    PCT_RIBOSOMAL_BASES: 100
    PCT_MRNA_BASES: 200
    PCT_PF_READS_ALIGNED: 300
    mapped_passed: 350
    FOLD_ENRICHMENT: 400
    PCT_TARGET_BASES_30X: 500
    summed_median: 600
    percent_duplicates: 700
    percent_gc: 800
    avg_sequence_length: 900
    total_sequences: 1000
```

and when I load it in MultiQC using the `--config` option I don't see the columns in the general stats table appear in the order indicated. Have I omitted something? I had been referencing https://multiqc.info/docs/reports/customisation/#column-order and think that my config is formatted the same way.

### Before submitting

- [x] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.
