### ISSUE TITLE
Boxplots for custom content

### ISSUE THREAD

**Issue by JohannesKersting** [MultiQC/MultiQC#2839]
### Description of feature

Hello :)

I really like the new boxplot plot type and think it would also be helpful as an option for visualizing custom content.
Are there any plans to make the plot type available for custom content as well?

Thanks a lot!

**Comment by vladsavelyev** [comment]
Hi! Thanks for the request. That makes sense! Added support for box plots. The format is roughly like for tables:

```yaml
id: 'custom_box_plot'
section_name: 'Custom box plot'
description: 'This is a custom content box plot.'
plot_type: 'box'
pconfig:
    id: 'custom_data_yaml_box_plot'
    title: 'Box plot from YAML'
data:
    sample_1: [1.2, 2.3, 3.112, 3.88, 4,1]
    sample_2: [1.3, 2.5, 1.1, 0.1, 4,5]
```
