### ISSUE TITLE
Specify colours for various categories in the newer version of MultiQC

### ISSUE THREAD

**Issue by sejmodha** [MultiQC/MultiQC#2940]
Hi,

I am trying to "upgrade" existing MultiQC which is compatible with version 1.14 to the most recent version (1.25).

I am struggling to translate the colours from custom_data in the newer version. 

In the old config.yaml I had code that would apply appropriate colours:

```
custom_data:
  mapping_plot:
    file_format: "tsv"
    section_name: "Reference mapping distribution"
    description: 'This plot shows the number of reads mapped to user-defined references used to analyse this dataset.'
    plot_type: "bargraph"
    pconfig:
      id: 'mapping_bar_plot'
      title: 'Reads QC: Mapping results'


sp:
   mapping_plot:
     fn: '*_ref_mapping_stats.tsv'
  
custom_plot_config:
  mapping_bar_plot:
    Ref1:
      color: "#007597"
    Ref2:
      color: "#6e7864"
    Unmapped:
      color: "#a03300"
```

However, I am unable to replicate this in the newer version.

Snippet 1:
```
custom_data:
  mapping_plot:
    file_format: "tsv"
    section_name: "Reference mapping distribution"
    description: "This plot shows the number of reads mapped to user-defined references used to analyse this dataset."
    pconfig: 
      id: "mapping_bar_plot"
      title: "Reads QC: Mapping results"
      ymin: 0
    "Ref1": 
      "color": "#007597"
    "Ref2":
      "color": "#6e7864"
    "Unmapped": 
      "color": "#a03300"
```
Snippet 2:
```
custom_data:
  mapping_plot:
    file_format: "tsv"
    section_name: "Reference mapping distribution"
    description: "This plot shows the number of reads mapped to user-defined references used to analyze this dataset."
    # Ensure no plot_type is set, pconfig only includes recognized fields
    pconfig: 
      id: "mapping_bar_plot"
      title: "Reads QC: Mapping results"
      ymin: 0


categories:
 - name: "Ref1"
    color: "#007597"
 - name: "Ref2"
   color: "#6e7864"
 - name: "Unmapped"
    color: "#a03300"
```

Snippet 3:
```
custom_data:
  mapping_plot:
    file_format: "tsv"
    section_name: "Reference mapping distribution"
    description: "This plot shows the number of reads mapped to user-defined references used to analyze this dataset."
    # Ensure no plot_type is set, pconfig only includes recognized fields
    pconfig: 
      id: "mapping_bar_plot"
      title: "Reads QC: Mapping results"
      ymin: 0
      colors:
        "Ref1": "#007597"
        "Ref2": "#6e7864"
        "Unmapped": "#a03300"

```

I have tried all three options but none of them results in the custom coloured bars as expected. 

I wonder if I am missing something obvious here!

Thanks for your help in advance!
Sej
