### ISSUE TITLE
when using parent_id: under custom_data:, if the id contains an underscore (_), the section_comment for that module does not work.

### ISSUE THREAD

**Issue by Hanjiewu** [MultiQC/MultiQC#3079]
### Description of bug

When using `parent_id:` under `custom_data:`, if the `id` contains an underscore (`_`), the `section_comments:` for that module does not work. There is no error message and the contents of all subgroups display correctly; only the section_comments: are missing.

### File that triggers the error

```
custom_data:
    mlst:
        parent_id: 'Other_species'
        parent_name: "Other species grouped data"
        id: 'mlst'
        section_name: 'mlst'
        plot_type: 'table'

    amr_results:
        parent_id: 'Other_species'
        parent_name: "Other species grouped data"
        id: 'amr_results'
        section_name: 'amr_results'
        description: "Antimicrobial resistance and Virulence factors prediction"
        plot_type: 'table'

section_comments:
  mlst: "The program looks for exact matches (identity) to full length (length) alleles. Allele symbol <br />
        <ul><li> **n** means exact intact allele, i.e. **length and identity 100%**</li>
        <li> **~n** means novel full length allele similar to the assigned number n, i.e. **length 100%, identity >= 95%**</li>
        <li> **n?** means partial match to known allele n, i.e. **length >= 10%, identity >= 95%**</li>
        <li> **-** means allele missing, i.e. **length < 10%, identity < 95%**</li>
        <li> two numbers, e.g. **n,m** means **multiple alleles**</li></ul>"

  amr_results: "By default, MultiQC starts using **violin plots** when a table has **500 rows or more**"
    
sp:
    amr_results:
        fn: 'amr_combined.tsv'
    mlst:
        fn: 'mlst_combined.csv'
```

### MultiQC Error log

```console

```

### Before submitting

- [x] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [x] I am using the latest release of MultiQC.
- [x] I have included a full MultiQC log, not truncated.
- [x] I have attached an input file (**.zip** if necessary) that triggers the error.
