### ISSUE TITLE
String/Number format errors during report generation using custom config.yml

### ISSUE THREAD

**Issue by pkerbs** [MultiQC/MultiQC#3088]
Hi,
I am using a config file for the generation of a multiqc report (v1.26):
```
log_filesize_limit: 200000000000

custom_table_header_config:
  general_stats_table:
    mean_coverage:
      format: "{:,.5f}"
    median_coverage:
      format: "{:,.5f}"

decimalPoint_format: "."
thousandsSep_format: ","

read_count_multiplier: 1
read_count_prefix: ""
read_count_desc: ""

base_count_multiplier: 1
base_count_prefix: ""
base_count_desc: ""

long_read_count_multiplier: 1
long_read_count_prefix: ""
long_read_count_desc: ""
```

The report gets generated but unfortunately, I get errors for every module (samtools stats, nanoplot, hsmetrics) that look like this:
```
Error applying format string '{:,d}' to table value 'samtools_stats-reads_mapped': '1064717.0'. Unknown format code 'd' for object of type 'float'. Check if your format string is correct.
```

I did not had this error in version 1.21. Looking into the docs, I also didn't see any syntax change for the settings in my config-file.
What could be causing this? 

Thanks in advance
Paul
