### ISSUE TITLE
Custom data won't include header in multiqc_* file

### ISSUE THREAD

**Issue by audrey-bollas** [MultiQC/MultiQC#3106]
Hello, thanks for the great tool!

I am trying to add a simple table to the top of my report to add failed samples based on a metric. E.g., number of mapped reads. I have created a file for multiqc to find:
```
$cat results_dir/auxillary_files/fail_mapped_samples_num_table.csv
Sample,STAR uniquely mapped reads
SRR31139166_chr22,34152
```

Here I define the custom data in my multiqc_config.yml:
```
custom_data:
  fail_mapped_samples:
      file_format: "csv"
      file_glob: "results_dir/auxillary_files/fail_mapped_samples_num_table.csv"
      description: "Number of uniquely mapped reads per sample from STAR."
      plot_type: "table"
      headers:
        Sample: "Sample"
        STAR uniquely mapped reads: "STAR uniquely mapped reads"
```

The table is in the report, but it has no contents. On looking at the logs further, I see that it isn't parsing the input file correctly. Somehow the data multiqc is using in the report is missing the header:
```
$cat mqc_report/multiqc_report_data/multiqc_fail_mapped_samples.txt 
SRR31139166_chr22       34152
```

And here are the logs showing it can't find the header:
```
[2025-02-27 12:10:42] multiqc.core.exec_modules                          [DEBUG  ]  Running module: custom_content
[2025-02-27 12:10:42] multiqc.plots.table_object                         [DEBUG  ]  Table key 'Sample' not found in data for 'fail_mapped_samples'. Skipping. Check for possible typos between data keys and header keys
[2025-02-27 12:10:42] multiqc.plots.table_object                         [DEBUG  ]  Table key 'STAR uniquely mapped reads' not found in data for 'fail_mapped_samples'. Skipping. Check for possible typos between data keys and header keys
[2025-02-27 12:10:42] multiqc.report                                     [DEBUG  ]  Wrote data file multiqc_fail_mapped_samples.txt
[2025-02-27 12:10:42] multiqc.report                                     [DEBUG  ]  Wrote data file multiqc_fail_mapped_samples.json
```

I understand it is looking at this `mqc_report/multiqc_report_data/multiqc_fail_mapped_samples.txt` file and can't find the header, but it is unclear to my why the header is missing. (I can also omit providing the header names in the config but they are still missing from the `multiqc_fail_mapped_samples.txt ` file and therefore won't be included in the table). How can I get multiqc to write this file correctly? Thank you!

MultiQC version 1.27.1

**Comment by audrey-bollas** [comment]
Actually I believe I fixed this. I just needed to make the file name a .txt file rather than .csv. I originally tried writing a file with tab separators but multiqc was getting errors parsing it so I switched to comma delimited. Thanks

**Comment by vladsavelyev** [comment]
Correct config would contain an `sp` section, and I believe `file_glob` is not an available option. Plus `headers` should be a str - to - dict mapping, e.g.:

```
custom_data:
  fail_mapped_samples:
    file_format: "csv"
    description: "Number of uniquely mapped reads per sample from STAR."
    plot_type: "table"
    headers:
      Sample:
        title: "Sample"
      STAR uniquely mapped reads:
        title: "STAR uniquely mapped reads"

sp:
  fail_mapped_samples:
    fn: "fail_mapped_samples_num_table.csv"
```

(though in this case `headers` is completely redundant).

This works for me with MultiQC 1.27.1
