### ISSUE TITLE
Custom Content Ordering Oddness

### ISSUE THREAD

**Issue by jchorl** [MultiQC/MultiQC#3136]
Hi!

I noticed when calling `multiqc -f foo_mqc.yaml bar_mqc.yaml`, the order of outputs is different than calling `multiqc -f bar_mqc.yaml foo_mqc.yaml`. Intuitively it makes sense - multiqc orders based on the ordering of files passed in. Specifically within a custom content module, you may get foo first or bar first.

![Image](https://github.com/user-attachments/assets/a02ea1ba-fb1f-4e16-927d-c49d39583508)

And there's an easy solution - [just supply `report_section_order`](https://docs.seqera.io/multiqc/reports/customisation#order-of-module-and-module-subsection-output) and multiqc will sort however you want.

However this solution doesn't really work with an architecture like:

![Image](https://github.com/user-attachments/assets/0f03c341-0674-4139-981d-275b99866ebd)

The child tasks aren't ordered. They run in parallel and can finish in any order. So they don't each know how to order themselves, and they may be passed to multiqc in different orders (in a single multiqc run). Of course you could auto-generate a `report_section_order` depending on what inputs are produced, but that requires a bunch of preprocessing.

Which got me thinking:
- Should multiqc just sort custom-content module sections?
- If so, by what key?

Multiqc clearly separates data parsing/ingestion from [report ordering](https://github.com/MultiQC/MultiQC/blob/7a75a7eb482a36c8fe99363da37cc84362cbb147/multiqc/core/order_modules_and_sections.py#L11). So it would make sense for ordering-related code to go in the report-ordering part of the codebase, and not try to convince multiqc to ingest inputs in a different order. As an extension, the current behaviour could be viewed more as an accident rather than respecting the order of input args.

One possible solution is to just wrap `mod.sections` in `sorted(...)` here: https://github.com/MultiQC/MultiQC/blob/7a75a7eb482a36c8fe99363da37cc84362cbb147/multiqc/core/order_modules_and_sections.py#L84

However I'm worried that would break existing modules that add sections in a very deliberate order.

Another option is to add sorting logic here: https://github.com/MultiQC/MultiQC/blob/7a75a7eb482a36c8fe99363da37cc84362cbb147/multiqc/core/special_case_modules/custom_content.py#L363

The same way custom content modules get sorted, module sections could also be sorted by default. Don't like the default sorting? Add a `report_section_order`. But at least it sorts by default so it is deterministic!

I don't know that I'd consider this a bug because well, multiqc is respecting the order of inputs passed in. I'd argue though that's very seldom what the user wants - often you're specifying hundreds of files. Why not just sort the filenames being passed in to multiqc, or better just pass it a directory? Because filenames also probably aren't the ideal ordering for custom content. Alphabetical or natural sort ordering on section names seems like a very reasonable default.

Some example cc inputs if you want to play around:

bar_mqc.yaml:

```
id: "bar"
section_name: "Bar"
parent_id: "foobar"
parent_name: "foobar"
description: "This plot shows the first two components from a principal component analysis."
plot_type: "scatter"
pconfig:
  id: "pca_scatter_plot"
  title: "PCA Plot"
  xlab: "PC1"
  ylab: "PC2"
data:
  sample_1: { x: 12, y: 14 }
  sample_2: { x: 8, y: 6 }
  sample_3: { x: 5, y: 11 }
  sample_4: { x: 9, y: 12 }
```

foo_mqc.yaml:

```
id: "foo"
section_name: "Foo"
parent_id: "foobar"
parent_name: "foobar"
description: "This plot shows the first two components from a principal component analysis."
plot_type: "scatter"
pconfig:
  id: "pca_scatter_plot"
  title: "PCA Plot"
  xlab: "PC1"
  ylab: "PC2"
data:
  sample_1: { x: 12, y: 14 }
  sample_2: { x: 8, y: 6 }
  sample_3: { x: 5, y: 11 }
  sample_4: { x: 9, y: 12 }
```
