### ISSUE TITLE
Space Ranger module doesn't find web_summary.html pattern

### ISSUE THREAD

**Issue by gboscagli** [MultiQC/MultiQC#3237]
### Description of bug

Greetings all,
I'm using MultiQC v1.29 to get descriptive statistics of a project that includes two distinct Space Ranger runs. The project folder is organized like this:

```
project_folder
├── sample1/
│   └── outs/
│       ├──web_summary.html
├── sample2/
│   └── outs/
│       ├── web_summary.html
├──other_folder/
```
I'm running MultiQC from the project folder using a .yaml config file but, even if the tool scans all the subfolders, it isn't able to find the pattern for web_summary.html specified [here](https://docs.seqera.io/multiqc/modules/spaceranger) (reporting for clarity):

```
spaceranger/count_html:
  - contents: '"command":"Space Ranger","subcommand":"count"'
    fn: "*.html"
    num_lines: 20
  - contents: '"command": "Space Ranger", "subcommand": "count"'
    fn: "*.html"
    num_lines: 20
```

The run doesn't produce any error, so I guessed that the pattern it searches for isn't satisfied, and this is confirmed by failing to grep them with:
```
grep -m 1 '"command":"Space Ranger","subcommand":"count"' sample1/outs/web_summary.html
grep -m 1 '"command": "Space Ranger", "subcommand": "count"' sample1/outs/web_summary.html
```

I thought it could be a problem of how `web_summary.html` is produced by Space Ranger: I'm using a quite recent version of Space Ranger (3.1.3, released on Feb 6, 2025) while I saw that last updates to the MultiQC Space Ranger module trace back to July 2024.

At the moment I can't double-check if MultiQC works for the same samples analyzed with an older Space Ranger version, but it seems to me to be a low-hanging fruit.

### MultiQC Error log

```console

```

### Before submitting

- [x] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [x] I am using the latest release of MultiQC.
- [x] I have included a full MultiQC log, not truncated.
- [x] I have attached an input file (**.zip** if necessary) that triggers the error.
